export const TimelineIconConstant =
[
    'body_measurement',
    'contact_merged',
    'feedback_form',
    'signup_icon',
    'skill_set',
    'ticket',
    'update_customer',
    'diet_published',
    'counselling_created',
    'counseling_updated',
    'counselling_done',
    'subscription_created',
    'payment_captured',
    'csat_rating',
    'customer_tags',
    'call_record',
    'exercise_publish',
    'measurement_log',
    'water_log',
    'weight_log',
    'customer_creation',
    'customer_onboarding',
    'note_created',
    'note_updated',
    'coach_change',
    'yoga_set',
    'mind_publish',
    'subscription_updated'
]


export const TimelineType = [
    {id:'DIET_PUBLISHED',value:'DIET PUBLISHED'},
    {id:'COUNSELLING_CREATED',value:'COUNSELLING CREATED'},
    {id:'COUNSELLING_UPDATED',value:'COUNSELLING UPDATED'},
    {id:'COUNSELLING_DONE',value:'COUNSELLING DONE'},
    {id:'SUBSCRIPTION_CREATED',value:'SUBSCRIPTION CREATED'},
    {id:'PAYMENT_CAPTURED',value:'PAYMENT CAPTURED'},
    {id:'CSAT_RATING',value:'CSAT RATING'},
    {id:'CUSTOMER_TAGS',value:'CUSTOMER TAGS'},
    {id:'CALL_RECORD',value:'CALL RECORD'},
    {id:'CUSTOMER_TAGS',value:'CUSTOMER TAGS'},
    {id:'EXERCISE_PUBLISH',value:'EXERCISE PUBLISH'},
    {id:'MEASUREMENT_LOG',value:'MEASUREMENT LOG'},
    {id:'WATER_LOG',value:'WATER LOG'},
    {id:'WEIGHT_LOG',value:'WEIGHT LOG'},
    {id:'CUSTOMER_CREATION',value:'CUSTOMER CREATION'},
    {id:'CUSTOMER_UPDATE',value:'CUSTOMER UPDATE'},
    {id:'CUSTOMER_ONBOARDING',value:'CUSTOMER ONBOARDING'},
    {id:'NOTE_CREATED',value:'NOTE CREATED'},
    {id:'NOTE_UPDATED',value:'NOTE UPDATED'},
    {id:'COACH_CHANGE',value:'COACH CHANGE'},
    {id:'YOGA_SET',value:'YOGA SET'},
    {id:'MIND_PUBLISH',value:'MIND PUBLISH'},
    {id:'SUBSCRIPTION_UPDATED',value:'SUBSCRIPTION UPDATED'},
  ]