export const CONSTANTS_TEXT = {
  signup: 'signup',
  login: 'login',
  success: 'success',
  warning: 'warning',
  error: 'error',
  info: 'info',
  image: 'image',
  pdf: 'pdf',
  video: 'video',
  audio: 'audio',
  excerciseThumbnail: 'ExcerciseThumbnail',
  email: 'email',
  verify_otp_wrong: 'Please fill all digits',
  role: 'User-Role',
  token: 'Token',
  refresh: 'refreshToken',
  text: 'text',
  select: 'select',
  number: 'number',
  textarea: 'textarea',
  time: 'time',
  edit: 'edit',
  view: 'view',
  save: 'save',
  date: 'date',
  password: 'password',
  checkbox: 'checkbox',
  radio: 'radio',
  activity: 'activity',
  mind: 'mind',
  copy: 'copy',
  swap: 'swap',
  delete: 'delete',
  create: 'create',
  update: 'update',
  parent: 'parentMenu',
  sibling: 'siblingMenu',
  subchild: 'subchild',
  // user & affiration
  createUser: 'createUser',
  deleteUser: 'deleteUser',
  updateUser: 'updateUser',
  createAffiration: 'createAffiration',
  deleteAffiration: 'createAffiration',
};
